trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: production

stages:
- stage: Deploy
  jobs:
  - job: CloudflareWorkers
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: |
        envsubst < wrangler.toml.example > wrangler.toml
        npm install
        npm run deploy
      displayName: 'Deploy with Wrangler'
