trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  jobs:
  - job: CloudflareWorkers
    variables:
    - group: production
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: |
        envsubst < wrangler.toml.example > wrangler.toml
        npm install
        npm run deploy
      displayName: 'Deploy with Wrangler'
- stage: Scan
  jobs:
  - job: MendBolt
    steps:
    - task: WhiteSource@21
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)'
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Microsoft Security DevOps'
  - job: MsSec
    steps:
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Microsoft Security DevOps'
